version: '2'

services:
  consul:
    image: consul:1.7.1
    command: consul agent -dev -client 0.0.0.0 -ui -bootstrap -rejoin
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  adminer:
    image: adminer:4.7.5
    ports:
      - 8001:8080
    environment:
      ADMINER_DESIGN: ng9
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
